# Generated by Django 4.0.5 on 2024-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mediaType',
            field=models.TextField(default='NoneType'),
        ),
    ]
