# Generated by Django 4.0.5 on 2024-01-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post Title', max_length=255),
        ),
    ]
