# Generated by Django 4.0.5 on 2024-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_ip', models.TextField(default='none')),
                ('user_email', models.TextField()),
                ('user_gender', models.TextField()),
                ('user_birthday', models.TextField()),
                ('is_premium', models.TextField()),
                ('user_first_name', models.TextField()),
                ('user_last_name', models.TextField()),
                ('user_location', models.TextField()),
                ('user_liked_posts', models.TextField()),
            ],
        ),
    ]
