# Generated by Django 4.0.5 on 2024-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_members_is_premium_alter_members_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='submitted_by',
            field=models.TextField(default='none'),
        ),
    ]
