# Generated by Django 4.0.5 on 2024-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_post_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.TextField(default='0'),
        ),
    ]
