# Generated by Django 4.0.5 on 2024-02-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='profile_description',
            field=models.CharField(default='none', max_length=255, null=True),
        ),
    ]
