# Generated by Django 4.0.5 on 2024-02-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_members_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='profile_views',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='video_views',
            field=models.TextField(default='none', null=True),
        ),
    ]
