# Generated by Django 4.0.5 on 2024-02-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_members_profile_views_members_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_views',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='video_views',
            field=models.TextField(default='0', null=True),
        ),
    ]
