# Generated by Django 4.0.5 on 2024-02-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_members_profile_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default='none', null=True),
        ),
    ]
