# Generated by Django 4.0.5 on 2024-03-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.TextField(default='0', null=True),
        ),
    ]
