# Generated by Django 4.0.5 on 2024-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_post_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='play_id',
            field=models.TextField(default='9qWQdXQ3'),
        ),
    ]
