# Generated by Django 4.0.5 on 2024-03-02 07:19

from django.db import migrations, models
import website.app_functions


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_post_play_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='play_id',
            field=models.TextField(default=website.app_functions.generate_random_id),
        ),
    ]
