# Generated by Django 4.0.5 on 2024-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_post_play_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='dislikes',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='likes',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hearts',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(default='0', null=True),
        ),
    ]
