# Generated by Django 4.0.5 on 2024-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_members_dislikes_members_likes_post_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='t_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hearts',
        ),
        migrations.AddField(
            model_name='post',
            name='t_likes',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(default='0'),
        ),
    ]
