# Generated by Django 4.0.5 on 2024-03-11 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0021_remove_post_t_dislikes_remove_post_t_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='none', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_dislikes', models.ManyToManyField(blank=True, related_name='issues_dislikes', to=settings.AUTH_USER_MODEL)),
                ('issue_likes', models.ManyToManyField(blank=True, related_name='issues_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
