# Generated by Django 4.0.5 on 2024-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='main_problem',
            field=models.TextField(default='none', null=True),
        ),
    ]
