# Generated by Django 4.0.5 on 2024-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_issues_main_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedded',
            field=models.TextField(default='False', null=True),
        ),
    ]
