# Generated by Django 4.0.5 on 2024-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_post_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
