# Generated by Django 4.0.5 on 2024-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_members_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(default='0', null=True),
        ),
    ]
