# Generated by Django 4.0.5 on 2024-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(default='none', null=True),
        ),
    ]
