# Generated by Django 4.0.5 on 2024-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_post_created_at_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pornstars',
            field=models.TextField(default='none', null=True),
        ),
    ]
