# Generated by Django 4.0.5 on 2024-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_post_pornstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.TextField(default='0', null=True),
        ),
    ]
