# Generated by Django 4.0.5 on 2024-04-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='true_category',
            field=models.TextField(default='none', null=True),
        ),
    ]
