# Generated by Django 4.0.5 on 2024-04-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_post_true_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
